spring:
  application:
    name: kafka-AuditReport-consumer
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: dDBTfvcdM52
    url: jdbc:sqlserver://acnovate211.bomdimensions.com:1433;databaseName=qiwkKafka;rewriteBatchedStatements=true;trustServerCertificate=true;
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolBooks
  jpa:
#    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        type: trace
        dialect: org.hibernate.dialect.SQLServerDialect
        # default_schema:
        ddl-auto: update

#        generate_statistics: false
#        order_inserts: true
#        order_updates: true
#        jdbc:
#          batch_size: 50
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    # DEV Kafka
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
#      fetch.max.bytes : 52428800
#      max.partition.fetch.bytes : 1048576
#      fetch.max.wait.ms : 1000
      fetch-min-bytes: 100000
      max-poll-records: 10000
    listener:
      concurrency: 5
#      batch-listener: true
      ack-mode: MANUAL_IMMEDIATE

server:
  port: 8082

# Display full git information on /info
management:
  info:
    git:
      mode: full
oauth2:
  security:
    enabled: false
tcp.health:
  port: 5001
  retry: 3
kafka:
  topic:
    audit: WindchillETL

config:
  rest:
    baseURL: http://192.168.31.210/AuditReport/servlet/rest
    username: wcadmin
    password: wcadmin
  kafka:
    consumer:
#      topicNameToPartitionOffset:
#        "[master.audit.delete.dev]":
#          0: 0
#          1: 0
LOG_PATH : C:/newconsumerLog
#logging:
#  level:
#    org.hibernate.type: trace